### PR TITLE
Add docs for local .env vars, update .gitignore to handle .env.local …

### PR DESCRIPTION
**Pull request by brendanrsmith**
…files

### CODE REVIEW

**Review by echeng06 — CHANGES_REQUESTED** [review]
A couple things:

* Could you specify that you need Flywheel version `>= 0.19.0`? That's the version they added [pass through arguments](https://gitlab.com/flywheel-io/tools/app/cli/-/releases/0.19.0)
* The commands are a bit incorrect, for `fw-beta` you need to specify the pass through `--`
    * Can also link to the docs here: https://flywheel-io.gitlab.io/tools/app/cli/fw-beta/gear/run/#pass-through-arguments    
    * Need to specify the gear directory, e.g. `fw-beta gear run <gear> -- -e xx=yy`
    * For the .env file it's `fw-beta gear run <gear> -- --env-file .env`

**Review by bjkeller — DISMISSED** [review]
Grazie mille

**Comment by bjkeller** [comment]
sorry, didn't see Emily's review

**Comment by brendanrsmith** [comment]
Thanks for the catch, @echeng06 - should be clearer now.

**Review by echeng06 — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
